### ISSUE TITLE
Configure addable types correctly

### ISSUE THREAD

**Issue by mbaechtold** [4teamwork/ftw.contacts#53]
The MemberBlock is added to the addable types in the default profile: https://github.com/4teamwork/ftw.contacts/blob/master/ftw/contacts/profiles/default/types/Plone_Site.xml#L5

This should be done in the `simplelayout` profile instead.

**Comment by raphael-s** [comment]
There seems to be some special installation for `ftw.memberblock` in the simplelayout profile: https://github.com/4teamwork/ftw.contacts/blob/master/ftw/contacts/simplelayout/configure.zcml#L18

Also, tests on master seem to be failing (at least on my machine): #55
