### ISSUE TITLE
Why do we set a permission for a non-addable type?

### ISSUE THREAD

**Issue by raphael-s** [4teamwork/ftw.contacts#59]
https://github.com/4teamwork/ftw.contacts/blob/8b98afac742e45ed17a42ebe92f71a9d96a7658e/ftw/contacts/profiles/default/rolemap.xml#L9-L13

`ftw.contacts.Contact` type is only addable inside of `ftw.contacts.ContactFolder`. So I think it is not necessary to configure the add permission for it on a plone root level. 
Or is there a reason for this?

(cc @mbaechtold )

**Comment by jone** [comment]
If there is no workflow enabled, the site root definition is used recursively.
So the site-level definition does not only apply for items added to the site root, but it may be applied recursively.
Therefore it is good practice to do exactly that for all add permissions.

**Comment by mbaechtold** [comment]
Oh, I did not know that. Thanks for the explanation @jone.
