### ISSUE TITLE
Function not found: circle:1

### ISSUE THREAD

**Issue by djowett-ftw** [4teamwork/ftw.contacts#76]
`2019-11-13 15:23:31 ERROR scss.ast Function not found: circle:1`

In our plone logfile points to this module....

is this an easy fix?

**Comment by jone** [comment]
Is the origin in `ftw.contacts`? I think Kevin has once debugged that 🤔

**Comment by djowett-ftw** [comment]
According to my debugger it is this one.... 
https://github.com/4teamwork/ftw.contacts/blob/6ff5dc8c472c975ba82ccbde8a2ea82074c27116/ftw/contacts/resources/scss/contacts.scss#L16

**Comment by bierik** [comment]
@djowett-ftw 
I made a pull request to fix this in the pyscss repo -> https://github.com/Kronuz/pyScss/pull/357
The PR was merged on 04/08/2016 but the last release was on 09/07/2016
My opinion was always to use a different SCSS compiler such as https://github.com/sass/libsass-python which uses bindings to the libSass library. But this would mean to completely rebuild the scss parsing part in ftw.theming.

**Comment by djowett-ftw** [comment]
Oh - that's a pain.  Internal patch release of pyScss in the meantime maybe?

**Comment by maethu** [comment]
I don't really like internal releases of any packages. It will confuse us at some point. 
IMHO we just live with that right now

**Comment by djowett-ftw** [comment]
@maethu @bierik pyScss now has a 1.3.7 release (1.3.6 is broken), so we could pin it up in this product maybe.    (This error was getting in the way of Products.PDBDebugMode so I tried 1.3.7 for bl.web and it's working ok)

**Comment by maethu** [comment]
@djowett-ftw I would pin it up in ftw.theming (base implementation of all the scss functionality)
